### 업무 생성
POST http://localhost:6060/task/tasks
Content-Type: application/json

{
  "projectId": 1,
  "milestoneId": 1,
  "title": "Task Create",
  "content": "Task GOOD",
  "registerId": "marco"
}

### 해당 업무 조회
GET http://localhost:6060/task/tasks/1

### 프로젝트에 속한 업무 목록 조회
GET http://localhost:6060/task/tasks/project/1

### 업무 수정
PUT http://localhost:6060/task/tasks
Content-Type: application/json

{
  "taskId": 1,
  "milestoneId" : 1,
  "title" : "marcoman",
  "content" : "marcoboy"
}

### 업무 삭제
DELETE http://localhost:6060/task/tasks/1
