###
POST http://localhost:7070/account/users/signup
Content-Type: application/json

{
  "userId": "marco",
  "userPassword": "1234",
  "userEmail": "marco@nhnacademy.com"
}

###
GET http://localhost:7070/account/users

###
POST http://localhost:7070/account/users/login
Content-Type: application/json

{
  "userId": "marco"
}

###
PUT http://localhost:7070/account/users/changeStatusLeave/1

###
PUT http://localhost:7070/account/users/changeStatusRest/1

###
POST http://localhost:7070/account/users/email
Content-Type: application/json

{
  "userEmail": "marco@nhnacademy.com"
}